--
-- movimentacoes
--
CREATE TABLE taxa(
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	cobrado_id NUMBER REFERENCES pessoa(id),
	valor NUMBER (10, 2),
	cobrada_em DATE NOT NULL,
	CONSTRAINT pk_taxa PRIMARY KEY(id)
);