--
-- movimentacoes
--
CREATE TABLE movimentacao(
	id 					NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	pessoa_origem_id 	NUMBER REFERENCES pessoa(id),
	pessoa_destino_id 	NUMBER REFERENCES pessoa(id),
	conta_origem_id 	NUMBER REFERENCES conta_bancaria(id),
	conta_destino_id 	NUMBER REFERENCES conta_bancaria(id),
	valor 				NUMBER (10, 2),
	realizado_em 		DATE NOT NULL,
	CONSTRAINT pk_movimentacao PRIMARY KEY(id)
);